Fixing variable translation
Missed updating this one everywhere on the line.  $TEMP -> $temp

diff --git a/bin/wick-explorer b/bin/wick-explorer
--- a/bin/wick-explorer
+++ b/bin/wick-explorer
@@ -24,7 +24,7 @@ wickExplorer() {
     wickTempDir tempdir
 
     (
-        . "$explorer" > "$tempdir/stdout" 2> "$TEMP/stderr" || echo "$" > "$TEMP/fail"
+        . "$explorer" > "$tempdir/stdout" 2> "$tempdir/stderr" || echo "$" > "$tempdir/fail"
     )
 
     if [[ -f "$tempdir/fail" ]]; then
