Changing stderr redirect notation
It is possible that /dev does not exist or that redirecting to
/dev/stderr is not what we want.  Instead we just redirect echo's output
to >&2

diff --git a/bin/wick-formula b/bin/wick-formula
--- a/bin/wick-formula
+++ b/bin/wick-formula
@@ -19,13 +19,13 @@ wick-formula() {
     fi
 
     if [[ -z "$FORMULA" ]]; then
-        echo "You must specify a formula name." >> /dev/stderr
+        echo "You must specify a formula name." >&2
 
         return 1
     fi
 
     if ! wick-find LOCATION "formulas/$FORMULA"; then
-        echo "Unable to find formula $FORMULA" >> /dev/stderr
+        echo "Unable to find formula $FORMULA" >&2
 
         return 1
     fi
@@ -33,7 +33,7 @@ wick-formula() {
     if wick-in-array "$FORMULA" "${WICK_FORMULA_LIST[@]}"; then
         # Specifying the same formula is ok as long as the arguments are the same
         if ! wick-in-array "$FORMULA_ESCAPED$ARGS" "${WICK_FORMULA_LIST_WITH_ARGS[@]}"; then
-            echo "Formula specified multiple times with different arguments: $FORMULA" >> /dev/stderr
+            echo "Formula specified multiple times with different arguments: $FORMULA" >&2
             return 1
         else
             echo "Formula is already in list: $FORMULA"
diff --git a/lib/wick-get-url b/lib/wick-get-url
--- a/lib/wick-get-url
+++ b/lib/wick-get-url
@@ -19,7 +19,7 @@ wick-get-url() {
         return 0
     fi
 
-    echo "Unable to download url - no suitable programs found" >> /dev/stderr
+    echo "Unable to download url - no suitable programs found" >&2
     return 1
 }
 
