Fixing the failure code preservation

diff --git a/bin/wick-explorer b/bin/wick-explorer
--- a/bin/wick-explorer
+++ b/bin/wick-explorer
@@ -24,7 +24,8 @@ wickExplorer() {
     wickTempDir tempdir
 
     (
-        . "$explorer" > "$tempdir/stdout" 2> "$tempdir/stderr" || echo "$" > "$tempdir/fail"
+        . "$explorer" > "$tempdir/stdout" 2> "$tempdir/stderr" || echo "$?" > "$tempdir/fail"
+        :
     )
 
     if [[ -f "$tempdir/fail" ]]; then
