Allowing arguments passed to roles with wick-load-role

diff --git a/bin/wick-load-role b/bin/wick-load-role
--- a/bin/wick-load-role
+++ b/bin/wick-load-role
@@ -4,21 +4,19 @@ wick-load-role() {
     local LOCATION ROLE
 
     if [[ ${#@} -eq 0 ]]; then
-        echo "You must specify one or more roles."
+        echo "You must specify a role to load."
 
         return 1
     fi
 
-    while [[ ! -z "$1" ]]; do
-        if ! wick-find LOCATION "roles/$1"; then
-            echo "Unable to find role $1"
+    if ! wick-find LOCATION "roles/$1"; then
+        echo "Unable to find role $1"
 
-            return 1
-        fi
+        return 1
+    fi
 
-        echo "Using role $1 ($LOCATION)"
-        WICK_ROLE_DIR=${LOCATION%/*}
-        . "$LOCATION"
-        shift
-    done
+    shift
+    echo "Using role $1 ($LOCATION)"
+    WICK_ROLE_DIR=${LOCATION%/*}
+    . "$LOCATION" "$@"
 }
