Converting to use some Bash style standards
* All functions and global variables get documented.

* Function and variable documentation will follow TomDoc.

* Function names move from wick-thing to wickThing to be more POSIX
  compliant.

* Variable names move from THE_VAR to theVar to help guarantee they
  never conflict with a system variable.  When exported or intentionally
  public they will instead be prefixed (eg. WICK_FORMULA_LIST).

* README files are now generated from the documentation in the scripts.
  This closes issue #15.  Included a new `Makefile` and a patched
  version of `tomdoc.sh`.  (TomDoc)[http://tomdoc.org/] was made for
  Ruby but really worsk for (shell)[https://github.com/mlafeldt/tomdoc.sh].

* Change shebang's interpreter from `#!/bin/bash` to `#!/usr/bin/env bash`
  to be more portable.

diff --git a/bin/wick-explorer b/bin/wick-explorer
--- a/bin/wick-explorer
+++ b/bin/wick-explorer
@@ -1,41 +1,41 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
-# Run explorers on the target machine
+# Run explorers on the target machine.
 
-# Run an explorer
+# Public: Run an explorer.
 #
-# Parameters:
-#     $1:  Variable name for the result
-#     $2:  Formula name
-#     $3:  Explorer name
-# Returns true when explorer ran successfully, false otherwise
-wick-explorer() {
-    local EXPLORER TEMP
+# $1 - Variable name for the result
+# $2 - Formula name
+# $3 - Explorer name
+#
+# Returns true when explorer ran successfully, false otherwise.
+wickExplorer() {
+    local explorer tempdir
 
-    EXPLORER="formulas/$2/explorers/$3"
+    explorer="formulas/$2/explorers/$3"
 
-    if ! wick-find EXPLORER "$EXPLORER"; then
-        wick-error "Unable to find explorer: $EXPLORER"
+    if ! wickFind explorer "$explorer"; then
+        wickError "Unable to find explorer: $explorer"
 
         return 1
     fi
 
     # Run the explorer
-    wick-temp-dir TEMP
+    wickTempDir tempdir
 
     (
-        . "$EXPLORER" > "$TEMP/stdout" 2> "$TEMP/stderr" || echo "$" > "$TEMP/fail"
+        . "$explorer" > "$tempdir/stdout" 2> "$TEMP/stderr" || echo "$" > "$TEMP/fail"
     )
 
-    if [[ -f "$TEMP/fail" ]]; then
-        wick-error "Explorer failed: $EXPLORER"
-        wick-error "Status code:  $(<"$TEMP/fail")"
+    if [[ -f "$tempdir/fail" ]]; then
+        wickError "Explorer failed: $explorer"
+        wickError "Status code:  $(<"$tempdir/fail")"
 
         return 1
     fi
 
-    wick-debug "Explorer success"
-    wick-debug "$(<"$TEMP/stdout")"
+    wickDebug "Explorer success"
+    wickDebug "$(<"$tempdir/stdout")"
 
-    local "$1" && wick-indirect "$1" "$(<"$TEMP/stdout")"
+    local "$1" && wickIndirect "$1" "$(<"$tempdir/stdout")"
 }
diff --git a/bin/wick-formula b/bin/wick-formula
--- a/bin/wick-formula
+++ b/bin/wick-formula
@@ -1,111 +1,119 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# Public: List of formulas to execute.  It is better to log this list
+# instead of the one with arguments because arguments may contain
+# sensitive information.
+WICK_FORMULA_LIST=()
+
+# Public: List of formulas with their arguments.  Try to avoid logging these.
+WICK_FORMULA_LIST_WITH_ARGS=()
+
+# Public: Commands to execute in order to make the formula execute.  This
+# will only add an entry if there is a "run" script.
+WICK_FORMULA_COMMANDS=()
+
+# Public: Mark a formula as required for a given role or as a dependency
+# for other formulas.
 #
-# Mark a formula as required for a given role or as a dependency for other
-# formulas.
+# $1   - Formula to require
+# $2-@ - Arguments for formula's run script
 #
 # If the formula was already marked as required, this will error as long as
 # the arguments don't match and there are arguments for this invocation.
 #
-#     # Example
-#     wick-formula test --arg=1
-#     wick-formula test          # Will not error
-#     wick-formula test --blue   # Errors
-
-WICK_FORMULA_LIST=()
-WICK_FORMULA_LIST_WITH_ARGS=()
-WICK_FORMULA_COMMANDS=()
-
-# Mark a formula as required and pass arguments to the formula's run script.
+# Examples
 #
-# Parameters:
-#     $1: Formula to require
-#     $2-*:  Arguments for formula's run script
+#   wickFormula test --arg=1
+#   wickFormula test          # Will not error
+#   wickFormula test --blue   # Errors
+#
 # Returns true if formula was found and added to the list.
-wick-formula() {
-    local ARGS FILE FORMULA FORMULA_ESCAPED LOCATION PRESERVED_PWD TEMP
+wickFormula() {
+    local args file formula formulaEscaped location preservedPwd temp
 
-    FORMULA="$1"
-    wick-argument-string FORMULA_ESCAPED "$FORMULA"
+    formula="$1"
+    wickArgumentString formulaEscaped "$formula"
     shift
 
     if [[ $# -gt 0 ]]; then
-        wick-argument-string ARGS "$@"
-        ARGS=" $ARGS"
+        wickArgumentString args "$@"
+        args=" $args"
     else
-        ARGS=""
+        args=""
     fi
 
-    if [[ -z "$FORMULA" ]]; then
+    if [[ -z "$formula" ]]; then
         echo "You must specify a formula name." >&2
 
         return 1
     fi
 
-    if ! wick-find LOCATION "formulas/$FORMULA"; then
-        echo "Unable to find formula $FORMULA" >&2
+    if ! wickFind location "formulas/$formula"; then
+        echo "Unable to find formula $formula" >&2
 
         return 1
     fi
 
-    if [[ "${#WICK_FORMULA_LIST[@]}" -gt 0 ]] && wick-in-array "$FORMULA" "${WICK_FORMULA_LIST[@]}"; then
+    if [[ "${#WICK_FORMULA_LIST[@]}" -gt 0 ]] && wickInArray "$formula" "${WICK_FORMULA_LIST[@]}"; then
         # Specifying the same formula is ok as long as the arguments are the same
-        if wick-in-array "$FORMULA_ESCAPED$ARGS" "${WICK_FORMULA_LIST_WITH_ARGS[@]}"; then
-            echo "Formula is already in list: $FORMULA"
+        if wickInArray "$formulaEscaped$args" "${WICK_FORMULA_LIST_WITH_ARGS[@]}"; then
+            echo "Formula is already in list: $formula"
+
             return 0
         fi
 
         # You can add the formula as a dependency with no arguments when it
         # was already added with arguments
-        if [[ "$ARGS" == "" ]]; then
-            echo "Formula is already in list and has additional arguments: $FORMULA"
+        if [[ "$args" == "" ]]; then
+            echo "Formula is already in list and has additional arguments: $formula"
             return 0
         fi
 
         # Mismatched arguments OR previously did not have arguments and current
         # one has arguments.  Do not continue.
-        echo "Formula specified multiple times with different arguments: $FORMULA" >&2
+        echo "Formula specified multiple times with different arguments: $formula" >&2
         return 1
     fi
 
     # Only use echo - do not log this to the file because the arguments
     # may contain secret keys.  Logging just the formula's name would be
     # acceptable.
-    echo "Adding formula $FORMULA$ARGS ($LOCATION)"
-    WICK_FORMULA_LIST[${#WICK_FORMULA_LIST[@]}]=$FORMULA
-    WICK_FORMULA_LIST_WITH_ARGS[${#WICK_FORMULA_LIST_WITH_ARGS[@]}]=$FORMULA_ESCAPED$ARGS
+    echo "Adding formula $formula$args ($location)"
+    WICK_FORMULA_LIST[${#WICK_FORMULA_LIST[@]}]=$formula
+    WICK_FORMULA_LIST_WITH_ARGS[${#WICK_FORMULA_LIST_WITH_ARGS[@]}]=$formulaEscaped$args
 
-    if [[ -f "$LOCATION/depends" ]]; then
-        # Can't run this in a subshell because subshells won't be able to
-        # modify parent variables, like WICK_FORMULA_LIST.
-        WICK_FORMULA_DIR=$LOCATION
-        PRESERVED_PWD=$PWD
+    if [[ -f "$location/depends" ]]; then
+        #: Can't run this in a subshell because subshells won't be able to
+        #: modify parent variables, like WICK_FORMULA_LIST.
+        WICK_FORMULA_DIR=$location
+        preservedPwd=$PWD
 
-        # See escaping note in wick-run-formula for why we are unable to use
-        #     . "$LOCATION/depends" $ARGS
-        eval "wick-strict-mode ; . \"$LOCATION/depends\" $ARGS"
-        cd "$PRESERVED_PWD"
+        # See escaping note in wickRunFormula for why we are unable to use
+        #     . "$location/depends" $args
+        eval "wickStrictMode ; . \"$location/depends\" $args"
+        cd "$preservedPwd"
     fi
 
-    if [[ -f "$LOCATION/run" ]]; then
-        wick-argument-string TEMP "$LOCATION/run"
-        WICK_FORMULA_COMMANDS[${#WICK_FORMULA_COMMANDS[@]}]=$TEMP$ARGS
+    if [[ -f "$location/run" ]]; then
+        wickArgumentString temp "$location/run"
+        WICK_FORMULA_COMMANDS[${#WICK_FORMULA_COMMANDS[@]}]=$temp$args
     fi
 
-    if [[ -d "$LOCATION/functions" ]]; then
-        for FILE in "$LOCATION/functions/"*; do
-            if [[ -f "$FILE" ]]; then
-                echo "Loading function: $FILE"
-                . "$FILE"
+    if [[ -d "$location/functions" ]]; then
+        for file in "$location/functions/"*; do
+            if [[ -f "$file" ]]; then
+                echo "Loading function: $file"
+                . "$file"
             fi
         done
     fi
 
-    if [[ -d "$LOCATION/explorers" ]]; then
-        for FILE in "$LOCATION/explorers/"*; do
-            if [[ -f "$FILE" ]]; then
-                echo "Running explorer: $FILE"
+    if [[ -d "$location/explorers" ]]; then
+        for file in "$location/explorers/"*; do
+            if [[ -f "$file" ]]; then
+                echo "Running explorer: $file"
                 (
-                    wick-explorer TEMP "$FORMULA" "${FILE##*/}"
+                    wickExplorer temp "$formula" "${file##*/}"
                 )
             fi
         done
diff --git a/bin/wick-load-role b/bin/wick-load-role
--- a/bin/wick-load-role
+++ b/bin/wick-load-role
@@ -1,33 +1,34 @@
-#!/bin/bash
-#
-# Locates a role file in the ancestry chain and loads it.  This will provide
-# a list of formulas to execute.
+#!/usr/bin/env bash
 
-# Load a role
+# Public: Locates a role file in the ancestry chain and loads it.  This
+# will provide a list of formulas to execute.
 #
-# Parameters:
-#     $1: Role to load
-#     $2-*: Extra arguments to pass to the role script
-# Returns true if there was no error loading the role
-wick-load-role() {
-    local LOCATION ROLE
+# When loading the role, sets `WICK_ROLE_DIR` to be the directory of
+# the role that is being loaded.
+#
+# $1   - Role to load
+# $2-@ - Extra arguments to pass to the role script
+#
+# Returns 1 if there is a problem loading the role.
+wickLoadRole() {
+    local location role WICK_ROLE_DIR
 
-    if [[ ${#@} -eq 0 ]]; then
+    if [[ $# -eq 0 ]]; then
         echo "You must specify a role to load."
 
         return 1
     fi
 
-    ROLE=$1
+    role=$1
     shift
 
-    if ! wick-find LOCATION "roles/$ROLE"; then
-        echo "Unable to find role $ROLE"
+    if ! wickFind location "roles/$role"; then
+        echo "Unable to find role $role"
 
         return 1
     fi
 
-    echo "Using role $ROLE ($LOCATION $@)"
-    WICK_ROLE_DIR=${LOCATION%/*}
-    . "$LOCATION" "$@"
+    echo "Using role $role ($@) at $location"
+    WICK_ROLE_DIR=${location%/*}
+    . "$location" "$@"
 }
diff --git a/lib/wick-command-exists b/lib/wick-command-exists
--- a/lib/wick-command-exists
+++ b/lib/wick-command-exists
@@ -1,7 +1,29 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Public: Tests to see if a command is in the path.  Because some systems
+# report failure in different ways, this is an attempt to abstract away those
+# alternate error messages and provide a consistent interface.
+#
+# $1 - Name of the command you wish to execute.  It would not make sense to
+#      use a full path here since the intent is to search the `PATH` for
+#      the command.
+#
+# Examples
+#
+#   if ! wickCommandExists ls; then
+#       echo 'Oh no, ls does not exist!'
+#       echo 'How do you list your files?'
+#       exit 1
+#   fi
+#
+# Returns 0 when found and an error status when the command was not found.
+wickCommandExists() {
+    local result
 
-wick-command-exists() {
-    RESULT=$(which ${1-} 2>&1)
+    if [[ -z "" ]]; then
+        return 5
+    fi
+
+    result=$(which ${1-} 2>&1)
 
     # Command failed to execute or reported failure
     if [[ $? -ne 0 ]]; then
@@ -9,17 +31,17 @@ wick-command-exists() {
     fi
 
     # Some OSs report "no PROGRAM_NAME"
-    if [[ "$RESULT" == "no "* ]]; then
+    if [[ "$result" == "no "* ]]; then
         return 2
     fi
 
     # Other OSs report "PROGRAM_NAME: no such program" or similar messages
-    if [[ "$RESULT" == *": no "* ]]; then
+    if [[ "$result" == *": no "* ]]; then
         return 3
     fi
 
     # Other times you can get "command not found"
-    if [[ "$RESULT" == *"command not found"* ]]; then
+    if [[ "$result" == *"command not found"* ]]; then
         return 4
     fi
 
diff --git a/lib/wick-debug-extreme b/lib/wick-debug-extreme
--- a/lib/wick-debug-extreme
+++ b/lib/wick-debug-extreme
@@ -1,8 +1,24 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Public: Turn on extreme logging.  This will alert you to all commands that
+# run.  When a command returns a non-zero exit code, that also will get
+# reported.
 #
-# Enable extreme debug logging
-
-wick-debug-extreme() {
+# $1 - When this is "stop" it disables the extreme logging.
+#
+# Examples
+#
+#   # This script may have errors, so turn on debugging
+#   wickDebugExtreme
+#
+#   if ! grep -q needle haystack.txt; then
+#       echo "No needle in haystack.txt"
+#   fi
+#
+#   # Stop the extreme logging
+#   wickDebugExtreme stop
+#
+# Returns nothing.
+wickDebugExtreme() {
     if [[ $# -eq 0 ]] || [[ "$1" != "stop" ]]; then
         export PS4='+\$?:$? (${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): } $BASH_COMMAND\n -> '
         set -x
diff --git a/lib/wick-error b/lib/wick-error
--- a/lib/wick-error
+++ b/lib/wick-error
@@ -1,25 +1,32 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Public: Logging function for errors.  Use this to log error messages right
+# before you exit the program or return a failure.  All messages are written to
+# stderr.  Log messages are also passed to the `wickLog` function to be logged
+# to a file.  (See `wickLog` for information about log files.  See
+# [Bash concepts](../doc/bash-concepts.md) for more about stderr.) This also
+# will colorize the output when the `WICK_COLOR` environment variable is set to
+# a non-empty string.
 #
-# Writes an error message to the logging system.
+# $@          - The message to log.  Arguments are joined into one line.
+# $WICK_COLOR - Colorizes output when set to a non-empty string.
 #
-# This message is always written to stderr.
+# Examples
 #
-# Parameters:
-#     $@: The log messages to write (they get joined into one line)
+#    wickError "Could not find some vital thing"
+#    exit 1
 #
-# Environment variables:
-#     WICK_COLOR: When set to non-empty string, ANSI color is enabled.
-wick-error() (
+# Returns nothing.
+wickError() (
     set +x
-    local CONTENT OUTPUT
+    local content output
 
-    wick-array-join CONTENT " " "$@"
-    wick-log "ERROR" "$CONTENT"
-    wick-prefix-lines OUTPUT "ERROR: " "$CONTENT"
+    wickArrayJoin content " " "$@"
+    wickLog "ERROR" "$content"
+    wickPrefixLines output "ERROR: " "$content"
 
     if [[ ! -z "${WICK_COLOR-}" ]]; then
-        OUTPUT=$'\E[41;37;1m'"$OUTPUT"$'\E[0m'
+        output=$'\E[41;37;1m'"$output"$'\E[0m'
     fi
 
-    echo "$OUTPUT" >&2
+    echo "$output" >&2
 )
diff --git a/lib/wick-get-iface-ip b/lib/wick-get-iface-ip
--- a/lib/wick-get-iface-ip
+++ b/lib/wick-get-iface-ip
@@ -1,40 +1,55 @@
-#!/bin/bash
-
-wick-get-iface-ip() {
-    local IP LIST OLD_IFS
+#!/usr/bin/env bash
+# Public: Determines the IP address associated with a given network interface.
+# If no interface is provided, this returns the first IP address listed by
+# `ifconfig`.
+#
+# $1 - Name of the variable that should receive the result.
+# $2 - Optional, network interface name.  If not specified, defaults to the
+#      first one returned by `ifconfig`.
+#
+# Examples
+#
+#   local ip
+#
+#   if ! wickGetIfaceIp ip tun0; then
+#       echo "Tunnel is not yet established"
+#       exit 1
+#   fi
+#
+#   echo "Tunnel IP:  $ip"
+#
+# Returns 0 on success, non-zero on failure.
+wickGetIfaceIp() {
+    local ip list
 
     if [[ "$2" == '*' ]]; then
-        LIST=()
-        OLD_IFS=$IFS
-        IFS=$'\n'
+        list=()
 
-        for IP in $(ifconfig -v 2>/dev/null | grep inet\ || echo ""); do
-            IP=${IP#*inet addr:}
-            IP=${IP#*inet }
-            IP=${IP%% *}
-            LIST[${#LIST[@]}]=$IP
-        done
+        while read ip; do
+            ip=${ip#*inet addr:}
+            ip=${ip#*inet }
+            ip=${ip%% *}
+            list[${#list[@]}]=$ip
+        done < <(ifconfig -v 2>/dev/null | grep 'inet ' || echo "")
 
-        IFS=$OLD_IFS
-
-        if [[ ${#LIST[@]} -eq 0 ]]; then
-            local "$1" && wick-indirect-array "$1"
-            return
+        if [[ ${#list[@]} -eq 0 ]]; then
+            local "$1" && wickIndirectArray "$1"
+            return 0
         fi
 
-        local "$1" && wick-indirect-array "$1" "${LIST[@]}"
+        local "$1" && wickIndirectArray "$1" "${list[@]}"
         return 0
     fi
 
-    IP=$(ifconfig -v $2 2>/dev/null | grep inet\ | head -n 1 || echo "")
-    IP=${IP#*inet addr:}
-    IP=${IP#*inet }
-    IP=${IP%% *}
+    ip=$(ifconfig -v $2 2>/dev/null | grep inet\ | head -n 1 || echo "")
+    ip=${ip#*inet addr:}
+    ip=${ip#*inet }
+    ip=${ip%% *}
 
-    if [[ -z "$IP" ]]; then
+    if [[ -z "$ip" ]]; then
         return 1
     fi
 
-    local "$1" && wick-indirect "$1" "$IP"
+    local "$1" && wickIndirect "$1" "$ip"
 }
 
diff --git a/lib/wick-get-url b/lib/wick-get-url
--- a/lib/wick-get-url
+++ b/lib/wick-get-url
@@ -1,61 +1,113 @@
-#!/bin/bash
-
-wick-get-url() {
+#!/usr/bin/env bash
+# Public: Download a URL, writing it to stdout or optionally saving it to a
+# file.  Uses `curl` or `wget` if installed on the system.
+#
+# $1                - URL to download.
+# $2                - Optional, filename to write with the resulting content.
+#                     When not specified, this writes to stdout.
+# --progress        - Show progress information during downloads.
+# --timeout=SECONDS - Give up after this many seconds elapse.
+#
+# Examples
+#
+#   # Download shell script execute it
+#   wickGetUrl --timeout=30 https://get.rvm.io/ | bash
+#
+#   # Download a large file and show progress information
+#   wickGetUrl --progress http://example.com/large-file.tar.gz /tmp/large-file.tgz
+#
+# Returns zero on success, non-zero if there is an error downloading.
+wickGetUrl() {
+    # These variables are intended to be used outside of wickGetUrl
+    # by the child functions for each command, thus they should be
+    # capitalized.
     local DEST PROGRESS TIMEOUT URL
 
-    wick-get-option PROGRESS progress "$@"
-    wick-get-option TIMEOUT timeout "$@"
-    wick-get-argument URL 0 "$@"
-    wick-get-argument DEST 1 "$@"
-    wick-debug "wick-get-url url: $URL"
-    wick-debug "wick-get-url dest: $DEST"
+    wickGetOption PROGRESS progress "$@"
+    wickGetOption TIMEOUT timeout "$@"
+    wickGetArgument URL 0 "$@"
+    wickGetArgument DEST 1 "$@"
+    wickDebug "wickGetUrl url: $URL"
+    wickDebug "wickGetUrl dest: $DEST"
 
-    if wick-command-exists curl; then
-        wick-get-url-curl || return 1
+    if wickCommandExists curl; then
+        wickGetUrlCurl || return 1
         return 0
     fi
 
-    if wick-command-exists wget; then
-        wick-get-url-wget || return 1
+    if wickCommandExists wget; then
+        wickGetUrlWget || return 1
         return 0
     fi
 
-    wick-error "Unable to download url - no suitable programs found"
+    wickError "Unable to download url - no suitable programs found"
     return 1
 }
 
-wick-get-url-curl() {
+
+# Internal: Download a file with curl.
+#
+# $DEST     - Destination filename or empty string for stdout.
+# $PROGRESS - Show progress bar when not an empty string.
+# $TIMEOUT  - Limit the command to run for the given number of seconds when
+#             this is not an empty string.
+# $URL      - The URL to download.
+#
+# Returns non-zero on error.
+wickGetUrlCurl() {
     local ARGS
 
     ARGS=(curl -L -f)
-    [[ -z "$PROGRESS" ]] && ARGS[${#ARGS[@]}]="-s"
-    [[ ! -z "$TIMEOUT" ]] && {
+
+    if [[ -z "$PROGRESS" ]]; then
+        ARGS[${#ARGS[@]}]="-s"
+    fi
+
+    if [[ ! -z "$TIMEOUT" ]]; then
         ARGS[${#ARGS[@]}]="-m"
         ARGS[${#ARGS[@]}]=$TIMEOUT
-    }
-    [[ ! -z "$DEST" ]] && {
+    fi
+
+    if [[ ! -z "$DEST" ]]; then
         ARGS[${#ARGS[@]}]="-o"
         ARGS[${#ARGS[@]}]=$DEST
-    }
+    fi
+
     ARGS[${#ARGS[@]}]=$URL
-    wick-debug "wick-get-url:" "${ARGS[@]}"
+    wickDebug "wickGetUrl:" "${ARGS[@]}"
     "${ARGS[@]}"
 }
 
-wick-get-url-wget() {
+
+# Internal: Download a file with curl.
+#
+# $DEST     - Destination filename or empty string for stdout.
+# $PROGRESS - Show progress bar when not an empty string.
+# $TIMEOUT  - Limit the command to run for the given number of seconds when
+#             this is not an empty string.
+# $URL      - The URL to download.
+#
+# Returns non-zero on error.
+wickGetUrlWget() {
     local ARGS
 
     ARGS=(wget)
-    [[ -z "$PROGRESS" ]] && ARGS[${#ARGS[@]}]="--quiet"
-    [[ ! -z "$TIMEOUT" ]] && {
+
+    if [[ -z "$PROGRESS" ]]; then
+        ARGS[${#ARGS[@]}]="--quiet"
+    fi
+
+    if [[ ! -z "$TIMEOUT" ]]; then
         ARGS[${#ARGS[@]}]="--timeout"
         ARGS[${#ARGS[@]}]=$TIMEOUT
-    }
-    [[ ! -z "$DEST" ]] && {
+    fi
+
+    if [[ ! -z "$DEST" ]]; then
         ARGS[${#ARGS[@]}]="-O"
         ARGS[${#ARGS[@]}]=$DEST
-    }
+    fi
+
     ARGS[${#ARGS[@]}]=$URL
-    wick-debug "wick-get-url:" "${ARGS[@]}"
+    wickDebug "wickGetUrl:" "${ARGS[@]}"
     "${ARGS[@]}"
 }
diff --git a/lib/wick-port-up b/lib/wick-port-up
--- a/lib/wick-port-up
+++ b/lib/wick-port-up
@@ -1,5 +1,29 @@
-#!/bin/bash
-wick-port-up() {
+#!/usr/bin/env bash
+# Public: Determines if a port is open or not.  Works with TCP and UDP ports.
+# If the port is open this returns an error code of 0.  If the port is not open
+# it returns 1.  If there are any errors this returns 2 and writes an error
+# message to stderr.  (See [Bash concepts](../doc/bash-concepts.md) for error
+# codes and stderr.)
+#
+# $1 - Protocol.  One of TCP, tcp, UDP, udp.
+# $2 - Port number to test.
+#
+# Examples
+#
+#   # Confirm a web server is listening
+#   if ! wickPortUp TCP 80; then
+#       echo "There is no web server listening on port 80."
+#   fi
+#
+#   # Wait for a server to start
+#   wickService start my-web-server
+#
+#   if ! wickWaitFor 120 wickPortUp TCP 80; then
+#       echo "Tried to wait for 2 minutes but nothing listened on port 80"
+#   fi
+#
+# Returns true on success and non-zero for any failure.
+wickPortUp() {
     local PORT RESULT
 
     PORT=$2
@@ -14,7 +38,7 @@ wick-port-up() {
             ;;
 
         *)
-            wick-error "Only accepts 'tcp' or 'udp', not '$2'"
+            wickError "Only accepts 'tcp' or 'udp', not '$1'"
             return 2
             ;;
     esac
diff --git a/lib/wick-strict-mode b/lib/wick-strict-mode
--- a/lib/wick-strict-mode
+++ b/lib/wick-strict-mode
@@ -1,19 +1,44 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Enables [strict mode] for Bash, based off [unofficial bash strict mode].
+# Errors will kill the program.  Accessing undefined variables will cause
+# errors (and exit the program).  Commands in pipelines that return a non-zero
+# status code will also cause errors and kill the program.  An ERR trap is also
+# enabled that will produce a stack trace when errors happen.
 #
-# Enables something as close as possible to a "strict mode" in Bash.
+# This is intended to be used at the beginning of your shell scripts in order
+# to ensure correctness in your programming.
 #
-# See http://redsymbol.net/articles/unofficial-bash-strict-mode/
-
-wick-strict-mode() {
+# Please check out the detailed explanation of [strict mode] for further
+# information.
+#
+# Examples
+#
+#   #!/usr/bin/env bash
+#   . /usr/local/lib/wick-infect
+#   wickStrictMode
+#
+# [unofficial bash strict mode]: http://redsymbol.net/articles/unofficial-bash-strict-mode/
+#
+# [strict mode]: ../docs/bash-strict-mode.md
+#
+# Returns nothing.
+wickStrictMode() {
     set -eEu -o pipefail
     shopt -s extdebug
     IFS=$'\n\t'
-    trap 'wick-strict-mode-fail $?' ERR
+    trap 'wickStrictModeFail $?' ERR
 }
 
-wick-strict-mode-fail() (
+
+# Internal: The ERR trap calls this function to report on the error location
+# right before dying.  See `wickStrictMode` for further details.
+#
+# $1 - Status from failed command.
+#
+# Returns nothing.
+wickStrictModeFail() (
     set +x
-    local ARGS_LIST ARGS_LEFT I NEXT_ARG
+    local argsList argsLeft i nextArg
 
     echo "Error detected - status code $1"
     echo "Command:  $BASH_COMMAND"
@@ -23,39 +48,39 @@ wick-strict-mode-fail() (
         echo "Pipe status: " "${PIPESTATUS[@]}"
     fi
 
-    I=$#
-    NEXT_ARG=$#
+    i=$#
+    nextArg=$#
 
-    if [[ $I -lt ${#BASH_LINENO[@]} ]]; then
+    if [[ $i -lt ${#BASH_LINENO[@]} ]]; then
         echo "Stack Trace:"
     else
         echo "Stack trace is unavailable"
     fi
 
-    while [[ $I -lt ${#BASH_LINENO[@]} ]]; do
-        ARGS_LIST=()
+    while [[ $i -lt ${#BASH_LINENO[@]} ]]; do
+        argsList=()
 
-        if [[ ${#BASH_ARGC[@]} -gt $I ]] && [[ ${#BASH_ARGV[@]} -ge $(( NEXT_ARG + ${BASH_ARGC[I]} )) ]]; then
-            for (( ARGS_LEFT = ${BASH_ARGC[I]}; ARGS_LEFT; --ARGS_LEFT )); do
+        if [[ ${#BASH_ARGC[@]} -gt $i ]] && [[ ${#BASH_ARGV[@]} -ge $(( nextArg + ${BASH_ARGC[i]} )) ]]; then
+            for (( argsLeft = ${BASH_ARGC[i]}; argsLeft; --argsLeft )); do
                 # Note: this reverses the order on purpose
-                ARGS_LIST[$ARGS_LEFT]=${BASH_ARGV[NEXT_ARG]}
-                (( NEXT_ARG ++ ))
+                argsList[$argsLeft]=${BASH_ARGV[nextArg]}
+                (( nextArg ++ ))
             done
 
-            if [[ ${#ARGS_LIST[@]} -gt 0 ]]; then
-                printf -v ARGS_LIST " %q" "${ARGS_LIST[@]}"
+            if [[ ${#argsList[@]} -gt 0 ]]; then
+                printf -v argsList " %q" "${argsList[@]}"
             else
-                ARGS_LIST=""
+                argsList=""
             fi
 
-            if [[ ${#ARGS_LIST} -gt 255 ]]; then
-                ARGS_LIST=${ARGS_LIST:0:250}...
+            if [[ ${#argsList} -gt 255 ]]; then
+                argsList=${argsList:0:250}...
             fi
         else
-            ARGS_LIST=""
+            argsList=""
         fi
 
-        echo "    [$I] ${FUNCNAME[I]:+${FUNCNAME[I]}(): }${BASH_SOURCE[I]}, line ${BASH_LINENO[I - 1]} -> ${FUNCNAME[I]:-${BASH_SOURCE[I]##*/}}$ARGS_LIST"
-        (( I ++ ))
+        echo "    [$i] ${FUNCNAME[i]:+${FUNCNAME[i]}(): }${BASH_SOURCE[i]}, line ${BASH_LINENO[i - 1]} -> ${FUNCNAME[i]:-${BASH_SOURCE[i]##*/}}$argsList"
+        (( i ++ ))
     done
 )
diff --git a/lib/wick-strict-run b/lib/wick-strict-run
--- a/lib/wick-strict-run
+++ b/lib/wick-strict-run
@@ -1,18 +1,38 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Public: Runs a command and captures its return code, even when [strict mode]
+# is enabled.  The variable name you specify is set to the return code of the
+# command.
 #
-# Adds a way to get the result status or exit code from a function while
-# the rest of the code operates in strict mode (see `wick-strict-mode`).
+# $1   - Name of variable that should get the return value / status code.
+# $2-@ - Command and arguments to run.
+#
+# This is intended to be used along with `wickStrictMode`.
+#
+# Example:
+#
+#   #!/usr/bin/env bash
+#   . /usr/local/lib/wick-infect
+#   wickStrictMode
+#
+#   wickStrictRun result grep "some-string" /etc/some-file.cfg > /dev/null 2>&1
+#
+#   if [[ $result -eq 0 ]]; then
+#       wickInfo "some-string was found"
+#   else
+#       wickInfo "some-string was not found"
+#   fi
+#
+# Returns nothing.
+wickStrictRun() {
+    local dest result setOptions
 
-wick-strict-run() {
-    local DEST RESULT SET_OPTIONS
-
-    DEST=$1
+    dest=$1
     shift
-    SET_OPTIONS=$-
+    setOptions=$-
     set +eE
     "$@"
-    RESULT=$?
-    set -"$SET_OPTIONS"
+    result=$?
+    set -"$setOptions"
 
-    local "$DEST" && wick-indirect "$DEST" "$RESULT"
+    local "$dest" && wickIndirect "$dest" "$result"
 }
diff --git a/lib/wick-wait-for b/lib/wick-wait-for
--- a/lib/wick-wait-for
+++ b/lib/wick-wait-for
@@ -1,9 +1,37 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Public: Wait a given amount of time for a shell script to return success,
+# waiting 1 second between calls.  If the time elapses without any successful
+# response then this returns failure.  Otherwise this returns success.
+#
+# $1   - Timeout, specified in seconds.
+# $2-@ - The command and arguments to pass to the command.
+#
+# If the timeout is reached, the running command is killed and `wickWaitFor`
+# will return failure.  Otherwise, `wickWaitFor` will return the status code
+# from the command.
+#
+# The command is executed directly.  Bash built-ins will not work.  Instead
+# of using `[[`, you must resort to `test`, `[` or writing a function that
+# can be called.
+#
+# Examples
+#
+#   /usr/local/bin/some-other-process &
+#
+#   # Wait up to 30 seconds for a file to exist
+#   # You must use a shell command here.  Bash built-ins won't work,
+#   # so use `[` or `test` instead of `[[`.
+#   if ! wickWaitFor 30 [ -f /var/run/other-process/run.lock ]; then
+#       echo "File was not created in time"
+#       exit 1
+#   fi
+#
+# Returns the command's status code.  The command may have been killed and
+# will typically return failure in that scenario.
+wickWaitFor() {
+    local latchProcess result sleepProcess sleepTime
 
-wick-wait-for() {
-    local LATCH_PROCESS RESULT SLEEP_PROCESS SLEEP_TIME
-
-    SLEEP_TIME=$1
+    sleepTime=$1
     shift
 
     # Run everything in a subshell to automatically enable monitor mode (set +m)
@@ -16,29 +44,29 @@ wick-wait-for() {
             done
             echo "latch success"
         ) > /dev/null 2>&1 &
-        LATCH_PROCESS=$!
+        latchProcess=$!
 
         # The timeout
         (
-            sleep $SLEEP_TIME
-            kill "$LATCH_PROCESS"
+            sleep $sleepTime
+            kill "$latchProcess"
         ) > /dev/null 2>&1 &
-        SLEEP_PROCESS=$!
+        sleepProcess=$!
 
         # Delay until one of the processes finish
         # Avoid "wait -n" because older bash does not support it
         # This also hides a "Terminated" message
-        wait $LATCH_PROCESS > /dev/null 2>&1
-        RESULT=$?
+        wait $latchProcess > /dev/null 2>&1
+        result=$?
 
         # On success, the timeout process is likely still running
-        if [[ $RESULT -eq 0 ]]; then
-            kill $SLEEP_PROCESS > /dev/null 2>&1
+        if [[ $result -eq 0 ]]; then
+            kill $sleepProcess > /dev/null 2>&1
         fi
 
         # Clean up and hide the "Terminated" message from killing bash
-        wait $SLEEP_PROCESS > /dev/null 2>&1
+        wait $sleepProcess > /dev/null 2>&1
 
-        return $RESULT
+        return $result
     ) || return 1
 }
