Enabling strict mode - more changes
Lots of issues with this strict mode.  For instance, appending to an
array used to be simple:

   ARR=("${ARR[@]}" "next")

That now gives an undefined variable warning.  Created wick-array-append
to counter that issue and started to check the length of the array
before using the array.

diff --git a/lib/wick-error b/lib/wick-error
--- a/lib/wick-error
+++ b/lib/wick-error
@@ -6,13 +6,11 @@
 #
 # Parameters:
 #     $*: The log message to write
-wick-error() {
-    (
-        set +x
-        local OUTPUT
+wick-error() (
+    set +x
+    local OUTPUT
 
-        wick-log "ERROR" "$*"
-        wick-prefix-lines OUTPUT "ERROR: " "$*"
-        echo "$OUTPUT" >&2
-    )
-}
+    wick-log "ERROR" "$*"
+    wick-prefix-lines OUTPUT "ERROR: " "$*"
+    echo "$OUTPUT" >&2
+)
diff --git a/lib/wick-strict-mode b/lib/wick-strict-mode
--- a/lib/wick-strict-mode
+++ b/lib/wick-strict-mode
@@ -5,6 +5,21 @@
 # See http://redsymbol.net/articles/unofficial-bash-strict-mode/
 
 wick-strict-mode() {
-    set -euo pipefail
+    set -eEuo pipefail
     IFS=$'\n\t'
+    trap 'wick-strict-mode-fail $?' ERR
+}
+
+wick-strict-mode-fail() {
+    local I
+    echo "Error detected - status code $1"
+    echo "Command:  $BASH_COMMAND"
+    echo "Location:  ${BASH_SOURCE[0]}, line ${BASH_LINENO[0]}"
+    echo "Stack Trace:"
+    I=0
+
+    while [[ $I -lt ${#BASH_LINENO} ]]; do
+        echo "    [$I] ${FUNCNAME[$I]:+${FUNCNAME[$I]}(): }${BASH_SOURCE[$I]}, line ${BASH_LINENO[$I]}"
+        I=$(($I + 1))
+    done
 }
