Updating code to work with newer versions of Bash
As it mentions in doc/contexts-that-disable-exit-on-error, this is a
problem that comes with newer versions of Bash.  It seems to appear
somewhere on or just before Bash 4.3.

It's a LOT of updates because I also ran ShellCheck against all of the
shell scripts, updated examples, and fixed things that were not up to
the Tests Always Included style guide.

diff --git a/formulas/wick-init-d-lib/files/wick-init-d-lib b/formulas/wick-init-d-lib/files/wick-init-d-lib
--- a/formulas/wick-init-d-lib/files/wick-init-d-lib
+++ b/formulas/wick-init-d-lib/files/wick-init-d-lib
@@ -89,6 +89,7 @@ handle-command() {
     renameFunction stop-fail stopFail
     renameFunction stop-success stopSuccess
     handleCommand
+
     return $?
 }
 
@@ -137,9 +138,10 @@ handleCommand() {
 #
 #   help
 #
-# Returns 1 (failure) always.
+# Exits with 1 (failure) always.
 help() {
     echo "Usage: $NAME {start|stop|restart|reload|status}" >&2
+
     exit 1
 }
 
@@ -159,8 +161,9 @@ isRunning() {
         return 1
     fi
 
-    if ! ps `getPid` > /dev/null 2>&1; then
+    if ! ps "$(getPid)" > /dev/null 2>&1; then
         cleanupFiles
+
         return 1
     fi
 
@@ -177,7 +180,7 @@ isRunning() {
 #
 # Returns nothing.
 processReload() {
-    kill -HUP `getPid`
+    kill -HUP "$(getPid)"
 }
 
 
@@ -196,6 +199,7 @@ processReload() {
 processStart() {
     echo "Misconfigured init script"
     echo "This function must be overridden"
+
     exit 1
 }
 
@@ -208,7 +212,7 @@ processStart() {
 #
 # Returns nothing.
 processStop() {
-    kill -INT `getPid`
+    kill -INT "$(getPid)"
 }
 
 
@@ -224,6 +228,7 @@ processStop() {
 reload() {
     if ! isRunning; then
         echo "$NAME is not running"
+
         return 0
     fi
 
@@ -234,6 +239,7 @@ reload() {
     if ! isRunning; then
         echo " $NAME has died, see $LOGFILE"
         reloadFail
+
         return 1
     fi
 
@@ -300,6 +306,7 @@ renameFunction() {
         if [[ "$functionName" == "$1" ]]; then
             # Make the new name simply call through to the old name.
             eval "$2 () { $1 \"\$@\" ; return \$? ; }"
+
             return 0
         fi
     done
@@ -326,6 +333,7 @@ restart() {
     if isRunning; then
         echo "Unable to stop $NAME, will not attempt to start."
         restartFail
+
         return 1
     fi
 
@@ -333,6 +341,7 @@ restart() {
 
     if [[ $? -ne 0 ]]; then
         restartFail
+
         return 2
     fi
 
@@ -385,10 +394,9 @@ restartSuccess() {
 #
 # Returns true on success, or different failure status codes.
 start() {
-    local PID
-
     if isRunning; then
         echo "$NAME already running"
+
         return 1
     fi
 
@@ -399,11 +407,13 @@ start() {
     if ! isRunning; then
         echo " unable to start $NAME, see $LOGFILE"
         startFail
+
         return 1
     fi
 
     echo " ok"
     touch "/var/lock/subsys/$NAME"
+
     startSuccess || return 3
 }
 
@@ -457,6 +467,7 @@ status() {
         echo "$NAME is running"
     else
         echo "$NAME is stopped"
+
         return 1
     fi
 }
@@ -474,6 +485,7 @@ status() {
 stop() {
     if ! isRunning; then
         echo "$NAME not running"
+
         return 0
     fi
 
@@ -481,6 +493,7 @@ stop() {
     stopBefore
     processStop
 
+    # shellcheck disable=SC2034
     for I in {1..10}; do
         if ! isRunning; then
             break
@@ -493,11 +506,13 @@ stop() {
     if isRunning; then
         echo " $NAME not stopped; may still be shutting down or shutdown may have failed - see $LOGFILE"
         stopFail
+
         return 1
     fi
 
     echo " stopped"
     cleanupFiles
+
     stopSuccess || return 3
 }
 
